packages:
  - "packages/*"

catalog:
  "@types/react": ^19.0.10
  "@types/react-dom": ^19.0.4
  "@vitejs/plugin-react": ^4.3.4
  react: ^19.0.0
  react-dom: ^19.0.0
  typescript: ^5.7.3
  vite: ^6.1.1
  vite-tsconfig-paths: ^5.1.4
